name: Build and Test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt install -y cmake build-essential
      - uses: actions/checkout@v4
      - name: CMake
        run: cmake .
      - name: Build Project
        run: make
      - name: Run Tests
        run: make test
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt install -y cmake build-essential clang
      - uses: actions/checkout@v4
      - name: CMake
        run: cmake -DCMAKE_BUILD_TYPE=Coverage .
      - name: Build Project
        run: make
      - name: Run Tests
        run: make test
      - name: Create coverage report
        run: make cov_report
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
